/*
 * generated by Xtext 2.10.0
 */
package br.edu.ifce.tests

import br.edu.ifce.maker.Curso
import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(MakerInjectorProvider)
class MakerParsingTest{

	@Inject
	ParseHelper<Curso> parseHelper

	@Test 
	def void testCurso() {
		val result = parseHelper.parse('''
			curso 'Inteligência Artificial' {
				descricao 'Mais um curso de IA'
				instituicao 'IFCE - Fortaleza'
			}
		''')
		
		val name = result.name
		val descricao = result.descricao.value
		val insituicao = result.instituicao.value
		
		Assert.assertEquals(name, 'Inteligência Artificial')
		Assert.assertEquals(descricao, 'Mais um curso de IA')
		Assert.assertEquals(insituicao, 'IFCE - Fortaleza')
	}

}
