/*
 * generated by Xtext 2.10.0
 */
package ioseph.francis


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BrandStandaloneSetup extends BrandStandaloneSetupGenerated {

	def static void doSetup() {
		new BrandStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
