/*
 * generated by Xtext 2.10.0
 */
package ioseph.francis


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BrandRuntimeModule extends AbstractBrandRuntimeModule {
}
