/*
 * generated by Xtext 2.10.0
 */
package br.edu.ifce


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MakerStandaloneSetup extends MakerStandaloneSetupGenerated {

	def static void doSetup() {
		new MakerStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
